# Generated by Django 5.1.2 on 2024-11-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desc',
            new_name='description',
        ),
    ]
